from demo/base

run curl -L -C - -b "oraclelicense=accept-securebackup-cookie" -O http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.rpm && \
    yum install -y ./*.rpm && \
    rm *.rpm
